name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_web:
    name: "check: web"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.0
      - name: install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: lint
        run: |
          cd web && bun i && bun format:check

  build_web:
    name: "build: web"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      - name: login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: get short commit hash for image tag
        id: shortened_hash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: ./web/
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/jflessau/inkday-web:latest
            ghcr.io/jflessau/inkday-web:${{ steps.shortened_hash.outputs.sha_short }}
